### ISSUE TITLE
Consider comparing Martin without memory cache

### ISSUE THREAD

**Issue by pka** [FabianRechsteiner/vector-tiles-benchmark#3]
Martin has a memory cache, which explains why only the first request for a tile takes some time and all following requests are returned immediately, without doing a database query. 

Since the benchmark concentrates on measuring live tile delivery from PostGIS, it seems appropriate to measure also with `cache_size_mb=0` (https://maplibre.org/martin/config-file.html?highlight=cache_size_mb#config-example). Martin log output has to contain `martin::config] Caching is disabled`.

Trying to do that, errors are returned after about 50 requests. The database log says:
```
postgis  | 2024-10-22 11:11:42.626 UTC [159] ERROR:  could not resize shared memory segment "/PostgreSQL.179755014" to 181088 bytes: No space left on device
```

Since disk space is available, it looks more like shared memory is exhausted?

EDIT: After adding `shm_size: '2gb'` to the `postgis` service, I was able to run the benchmark with Martin. Only the 100 threads/users tests returned errors, but this time
```
postgis  | 2024-10-22 11:53:57.290 UTC [2104] FATAL:  sorry, too many clients already
```
This is caused by the configured pool size 200 of Martin, which is more than the `max_connections = 100` PostgreSQL configuration.

**Comment by FabianRechsteiner** [comment]
Thanks for the insight!

In my master’s thesis, I used the default settings for the performance test, including `cache_size_mb`=512 for Martin. Ideally, setting this to 0 would have allowed for better comparability by measuring live data queries without caching.

I also made a few adjustments to avoid connection and memory issues during benchmarking: I set `shm_size` to 1 GB and increased `max_connections` to 200 to prevent errors from too many simultaneous connections.

Have you tried running the performance test without caching and comparing the results with a BBOX query? This might provide some additional insights.

**Comment by pka** [comment]
I did run the benchmark for Martin and BBOX with the following changes:

```diff
diff --git a/compose.yaml b/compose.yaml
index b3e4227..c18dff8 100644
--- a/compose.yaml
+++ b/compose.yaml
@@ -18,6 +18,7 @@ services:
   postgis:
     image: postgis/postgis:${POSTGRES_VERSION:-16-3.4-alpine}
     container_name: postgis
+    shm_size: '2gb'
     profiles: ["postgis","bbox","pg_tileserv","tipg","ldproxy","tegola","martin","all_server"]
     restart: always
     environment:
@@ -30,7 +31,7 @@ services:
       - 5432:5432
       
   bbox:
-    image: sourcepole/bbox-server-qgis:v0.5.0-beta1 #latest
+    image: sourcepole/bbox-server-qgis:v0.6.1 #latest
     container_name: bbox
     environment:
      - PGPASSWORD=${POSTGRES_USER_PASSWORD:-user_password}
@@ -65,8 +66,10 @@ services:
       - 7080:7080
 
   martin:
-    image: ghcr.io/maplibre/martin:v0.13.0
+    image: ghcr.io/maplibre/martin:v0.14.2
     container_name: martin
+    command: "--config /opt/martin_config/config.yaml"
+    # command: "--save-config /opt/martin_config/config14.yaml"
     environment:
       - DATABASE_URL=postgresql://${POSTGRES_USER_USERNAME:-user_name}:${POSTGRES_USER_PASSWORD:-user_password}@postgis/${POSTGRES_DB:-postgres_db}
     volumes:
diff --git a/martin/config.yaml b/martin/config.yaml
index d99b0b7..ab629e8 100644
--- a/martin/config.yaml
+++ b/martin/config.yaml
@@ -7,12 +7,17 @@
 # Number of web server workers
 #worker_processes: 8
 
+# Amount of memory (in MB) to use for caching tiles [default: 512, 0 to disable]
+cache_size_mb: 0
+
 # Database configuration. This can also be a list of PG configs.
-#postgres:
+postgres:
+  auto_publish: true
   # Database connection string. You can use env vars too, for example:
   #   $DATABASE_URL
   #   ${DATABASE_URL:-postgresql://postgres@localhost/db}
 #  connection_string: 'postgresql://postgres@localhost:5432/db'
+  connection_string: postgresql://postgres:password@postgis/postgres
 
   # Same as PGSSLCERT for psql
 #  ssl_cert: './postgresql.crt'
@@ -25,10 +30,10 @@
   default_srid: 2056 #4326
 
   # Maximum Postgres connections pool size [default: 20]
- pool_size: 200
+  pool_size: 80
 
   # Limit the number of table geo features included in a tile. Unlimited by default.
- max_feature_count: 10000
+  max_feature_count: 10000
 
   # Control the automatic generation of bounds for spatial tables [default: quick]
   # 'calc' - compute table geometry bounds on startup.
```

It did result in a much smaller difference over all tests.

**Comment by CommanderStorm** [comment]
@FabianRechsteiner Could you please apply the changes from @pka ?

Current results are quite misleading.
I think we are not doing ourselves a favor by comparing apples vs oranges here.

Martin and BBox should not be so far apart performance wise, we use similar tech.
I would expect a bit of a performance difference, but not much.

**Comment by CommanderStorm** [comment]
@pka does bbox have `max_feature_count`?
If it does not, we should use `max_feature_count: null` to be not unfair in this regard.

> Limit the number of geo features per tile.
> 
> If the source table has more features than set here, they will not be included in the tile and the result will look "cut off"/incomplete.
> This feature allows to put a maximum latency bound on tiles with extreme amount of detail at the cost of not returning all data.
> It is sensible to set this limit if you have user generated/untrusted geodata, e.g. a lot of data points at [Null Island](https://en.wikipedia.org/wiki/Null_Island).
> `max_feature_count: null` # either a positive integer, or null=unlimited (default)
